import { ReactNode } from "react";
import type { Metadata } from "next";
import { InterFont } from "theme/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: {
  //   icon: "",
  // },
  // other: {
  //   "theme-color": "#000000",
  //   "color-scheme": "dark",
  //   "twitter:title": "",
  //   "twitter:description": "",
  //   "twitter:url": "",
  //   "twitter:domain": "",
  //   "twitter:image": "",
  //   "twitter:card": "summary_large_image",
  //   "og:title": "",
  //   "og:description": "",
  //   "og:url": "",
  //   "og:image": "",
  //   "og:type": "website",
  // },
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={InterFont.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
